#!/bin/bash

# Loop through domains in scopes.txt
while IFS= read -r domain; do
    echo "Processing domain: $domain"

    # Create a folder for the domain's enumeration
    enum_dir="$HOME/automate/enum/$domain"
    mkdir -p "$enum_dir"
    # Run subfinder
    echo "starting subfinder"
    subfinder -d "$domain" -o "$enum_dir/subfinder.txt"
    # Run assetfinder
    echo "starting assetfinder"
    assetfinder --subs-only "$domain" | tee -a "$enum_dir/asset.txt"
    # Run crt_org.sh
    echo "starting crt_org"
    crt_org.sh "$domain" | tee -a "$enum_dir/crt_org.txt"
    # Run amass enum
    echo "starting amass as passive"
    timeout 30m amass enum --passive -d "$domain" | tee -a "$enum_dir/amassP.txt"
    # Run amass enum with brute
    echo "starting amass as brute"
    timeout 45m amass enum --brute -d "$domain" -v | tee -a "$enum_dir/amassB.txt"
    # Combine and sort unique domains
    cat "$enum_dir"/*.txt | sort -u > "$enum_dir/finalDomains.txt"
    # Check for alive subdomains
    cat "$enum_dir/finalDomains.txt" | httpx -silent -o "$enum_dir/alive.txt" | httpx -l "$enum_dir/alive.txt" -fr -title -status-code -location -content-length -websocket -td -o "$enum_dir/details.txt"

done < scopes.txt
